version: '3.8'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - .:/JERA  
  db:
    image: mysql:9.3.0
    volumes:
      - 'mysql-data:/var/lib/mysql:delegated'
    command: mysqld --sql_mode="" --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: password
    ports:
    - "3306:3306"

volumes:
  mysql-data: