site_name: Documentação

nav:
  - Visão do Produto e do Projeto:
      - visao/index.md
      - 1. Visão Geral do Produto: visao/01_produto.md
      - 2. Visão Geral do Projeto: visao/02_projeto.md
      - 3. Processo de Desenvolvimento de Software: visao/03_processo.md
      - 4. Declaração de Escopo do Projeto: visao/04_escopo.md
      - 5. Métricas e Medições: visao/05_metricas.md
      - 6. Testes de Software: visao/06_testes.md
      - 7. Referências Bibliográficas: visao/07_referencias.md

  - Documento de Arquitetura:
      - 1. Introdução: doc-arq/1_introducao.md
      - 2. Definições e Justificativas: doc-arq/2_definicoes-justificativa.md
      - 3. Detalhamento: doc-arq/3_detalhamento.md
      - 4. Metas e Restrições: doc-arq/4_metas-restricoes.md
      - 5. Casos de Uso: doc-arq/07_casos_de_uso.md
      - 6. Visão Lógica: doc-arq/8_visao-logica.md
      - 7. Visão de Implementação: doc-arq/9_visao-implementacao.md
      - 8. Visão de Implantação: doc-arq/10_visao-implantacao.md
      - 9. Restrições Adicionais: doc-arq/11_restricoes_adicionais.md
      - 10. Referências: doc-arq/12_referencias.md
      - Diagrama de Casos de Uso: doc-arq/diagrama_casos_uso_flora...

  - Atas de Reunião:
      - Ata 1: atas-reuniao/ata-reuniao-1.md
      - Ata 2: atas-reuniao/ata-reuniao-2.md
      - Ata 3: atas-reuniao/ata-reuniao-3.md
      - Ata 4: atas-reuniao/ata-reuniao-4.md
      - Ata 5: atas-reuniao/ata-reuniao-5.md

  - Instruções mkdocs: index.md

theme:
  name: material
  font:
    text: Roboto
    code: Roboto Mono
  icon:
    logo: fontawesome/solid/seedling
  features:
    - navigation.footer
    - navigation.tabs
    - navigation.expand
    - navigation.sections

  palette:
    - scheme: slate
      toggle:
        icon: material/weather-sunny
        name: Dark mode
      primary: red
      accent: deep purple

    - scheme: default
      toggle:
        icon: material/weather-night
        name: Light mode
      primary: blue
      accent: deep orange

markdown_extensions:
  - admonition
  - attr_list
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - toc:
      permalink: true
      toc_depth: 6

extra:
  social:
    - icon: simple/github
      link: https://github.com/FGA0138-MDS-Ajax/2025.1-Jera
