site_name: Documentação

nav:
  - Instruções mkdocs: "index.md"
  - Documento de Visão:
      - Perfis: "doc-arq/Perfis.md"
  - Documento de Arquitetura: "doc-arq/rep-arquitetural.md"
  - Atas de Reunião:
      - Ata 1: "atas-reuniao/ata-reuniao-1.md"
      - Ata 2: "atas-reuniao/ata-reuniao-2.md"
      - Ata 3: "atas-reuniao/ata-reuniao-3.md"
      - Ata 4: "atas-reuniao/ata-reuniao-4.md"
      - Ata 5: "atas-reuniao/ata-reuniao-5.md"

theme:
  name: material
  font:
    text: Roboto
    code: Roboto Mono
  icon:
    logo: fontawesome/solid/seedling
  features:
    - navigation.footer
    - navigation.tabs
  palette:
    # Dark Mode
    - scheme: slate
      toggle:
        icon: material/weather-sunny
        name: Dark mode
      primary: red
      accent: deep purple

    # Light Mode
    - scheme: default
      toggle:
        icon: material/weather-night
        name: Light mode
      primary: blue
      accent: deep orange

markdown_extensions:
  - attr_list
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences

extra:
  social:
    - icon: simple/github
      link: https://github.com/FGA0138-MDS-Ajax/2025.1-Jera
