site_name: Documentação

nav:
  - Visão do Produto e do Projeto:
      - 1. Visão Geral do Produto: visao/01_produto.md
      - 2. Visão Geral do Projeto: visao/02_projeto.md
      - 3. Processo de Desenvolvimento de Software: visao/03_processo.md
      - 4. Declaração de Escopo do Projeto: visao/04_escopo.md
      - 5. Métricas e Medições: visao/05_metricas.md
      - 6. Testes de Software: visao/06_testes.md
      - 7. Referências Bibliográficas: visao/07_referencias.md

  - Documento de Arquitetura: "doc-arq/rep-arquitetural.md"
  - Atas de Reunião:
      - Ata 1: "atas-reuniao/ata-reuniao-1.md"
      - Ata 2: "atas-reuniao/ata-reuniao-2.md"
      - Ata 3: "atas-reuniao/ata-reuniao-3.md"
      - Ata 4: "atas-reuniao/ata-reuniao-4.md"
      - Ata 5: "atas-reuniao/ata-reuniao-5.md"
  - Instruções mkdocs: "index.md"

plugins:
  - search
  - section-index
  - enumerate-headings:
      toc_depth: 6
      include:
        - "*"
      restart_increment_after:
          - visao/produto.md

theme:
  name: material
  font:
    text: Roboto
    code: Roboto Mono
  icon:
    logo: fontawesome/solid/seedling
  features:
    - navigation.footer
    - navigation.tabs
    - navigation.expand

  palette:
    # Dark Mode
    - scheme: slate
      toggle:
        icon: material/weather-sunny
        name: Dark mode
      primary: red
      accent: deep purple

    # Light Mode
    - scheme: default
      toggle:
        icon: material/weather-night
        name: Light mode
      primary: blue
      accent: deep orange

markdown_extensions:
  - admonition
  - attr_list
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - toc:
      permalink: true
      toc_depth: 6

extra:
  social:
    - icon: simple/github
      link: https://github.com/FGA0138-MDS-Ajax/2025.1-Jera
